### ISSUE TITLE
Feature Request: temporary Disable rope collsion

### ISSUE THREAD

**Issue by MizzyMizi** [timofey260/RWE-Plus#55]
A button / keybind, or other option for placing rope type props to disable the collision in case the prop's simulation isn't behaving well with the level's geometry.

Would it also be possible to add ZeroG and even up-sidedown for any rope prop via a buttons / menu settings too?

**Comment by MizzyMizi** [comment]
Sorry if this is wrong, but are the rope props while in ghost mode supposed to be un-placeable?

**Comment by timofey260** [comment]
bruh, maybe i missed this one out

**Comment by timofey260** [comment]
Fixed in next release

**Comment by MizzyMizi** [comment]
Thank you, looking forward to it~

**Comment by MizzyMizi** [comment]
Still can't place rope props while they are in ghost mode, now you can do even less while in ghost mode too? no rotated or scaling ect.

Maybe this was intended? if so just correct me

**Comment by timofey260** [comment]
you sure?
the patch changed key from shift to t(i'm too lazy to fix it because i'm working on rwe#)
